import React, { useState } from 'react';
export const formatBytes = bytes => bytes < 1024 * 1024 ? `${(bytes / 1024).toLocaleString('es-ES', { maximumFractionDigits: 1 })} KB` : `${(bytes / 1024 / 1024).toLocaleString('es-ES', { maximumFractionDigits: 1 })} MB`;
export const formatTime = ms => ms === null || ms === undefined ? 'Sin medir' : ms < 1000 ? `${Math.round(ms)} ms` : ms < 60000 ? `${(ms / 1000).toLocaleString('es-ES', { maximumFractionDigits: 1 })} s` : `${(ms / 60000).toLocaleString('es-ES', { maximumFractionDigits: 1 })} min`;
const number = n => (n || 0).toLocaleString('es-ES');
export function ProjectForm({ project, busy, onSave }) {
  const [name, setName] = useState(project?.name || ''), [description, setDescription] = useState(project?.description || '');
  return <form className="project-form" onSubmit={e => { e.preventDefault(); onSave({ name, description }); }}>
    <label>Nombre del proyecto<input required maxLength={120} placeholder="Libro, artículos, propuestas…" value={name} onChange={e => setName(e.target.value)}/></label>
    <label>Descripción (opcional)<input maxLength={1000} value={description} onChange={e => setDescription(e.target.value)}/></label>
    <button className="primary" disabled={busy || !name.trim()}>{project ? 'Guardar proyecto' : 'Crear proyecto'}</button>
  </form>;
}
export function Projects({ projects, busy, onOpen, onCreate, onDelete }) {
  return <><section className="card"><h2>Un espacio para cada trabajo</h2><p>Separa libros, artículos y otros textos. Cada proyecto conserva sus documentos, decisiones y estadísticas.</p><ProjectForm busy={busy} onSave={onCreate}/></section>
    <div className="project-grid">{projects.map(p => <article className="card project-card project-item" key={p.id}><button className="project-open" onClick={() => onOpen(p.id)}><span className="project-initial">{p.name.slice(0,1).toLocaleUpperCase('es-ES')}</span><h2>{p.name}</h2><p>{p.description || 'Sin descripción'}</p><div className="project-card-metrics"><span><strong>{number(p.statistics.documents)}</strong>{p.statistics.documents === 1 ? 'documento' : 'documentos'}</span><span><strong>{formatBytes(p.statistics.size_bytes)}</strong>PDF originales</span><span><strong>{number(p.statistics.pending)}</strong>pendientes</span></div><div className="project-card-footer"><span>{number(p.statistics.working)} en proceso · {number(p.statistics.completed)} {p.statistics.completed === 1 ? 'analizado' : 'analizados'}</span><span>Ver documentos →</span></div></button><DeleteProject compact project={p} busy={busy} onDelete={() => onDelete(p.id)}/></article>)}</div>
  </>;
}
export function Dashboard({ project, documents, busy, onOpen, onUpload, onSave, onDelete, stageNames }) {
  if (!project) return <p>Cargando proyecto…</p>;
  const s = project.statistics;
  const metrics = [['Tamaño de los PDF', formatBytes(s.size_bytes), `${number(s.documents)} ${s.documents === 1 ? 'documento guardado' : 'documentos guardados'}`], ['Frases analizadas', number(s.sentences), `${number(s.words)} palabras en páginas analizadas`], ['Hallazgos', number(s.findings), `${number(s.distinct_rules)} reglas con coincidencias`], ['Pendientes', number(s.pending), `${number(s.approved)} ${s.approved === 1 ? 'cambio aprobado' : 'cambios aprobados'} · ${number(s.kept)} ${s.kept === 1 ? 'conservado' : 'conservados'}`], ['Cobertura', `${number(s.analyzed)} / ${number(s.pages)}`, 'Páginas analizadas / páginas de PDF terminados'], ['Tiempo de procesamiento', s.timed_documents ? formatTime(s.processing_ms) : 'Sin medir', `${number(s.timed_documents)} ${s.timed_documents === 1 ? 'documento con duración registrada' : 'documentos con duración registrada'}`], ['Tiempo medio por PDF', formatTime(s.average_processing_ms), 'Solo análisis terminados con medición'], ['Tiempo en cola', s.timed_documents ? formatTime(s.queue_ms) : 'Sin medir', 'Espera acumulada de análisis terminados medidos']];
  return <><section className="card project-banner"><div><span className="eyebrow">PROYECTO</span><h2>{project.name}</h2><p>{project.description || 'Documentos y revisiones de este proyecto.'}</p></div><button className="primary" onClick={onUpload}>Subir un PDF</button></section>
    <div className="dashboard-metrics">{metrics.map(([label,value,detail]) => <section className="card dashboard-metric" key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></section>)}</div>
    <div className="dashboard-status"><span className="pill green">{s.completed} {s.completed === 1 ? 'analizado' : 'analizados'}</span><span className="pill blue">{s.working} en proceso</span><span className={`pill ${s.failed ? 'red' : ''}`}>{s.failed} {s.failed === 1 ? 'fallido' : 'fallidos'}</span><span className="pill">{s.cancelled} {s.cancelled === 1 ? 'cancelado' : 'cancelados'}</span></div>
    <p className="extraction-disclaimer">Las frases se cuentan con segmentación lingüística del texto extraído. Las coincidencias indican expresiones para revisar; incluyen las que decides conservar. Tamaño: PDF originales. {s.unmeasured_documents > 0 && `${s.unmeasured_documents} ${s.unmeasured_documents === 1 ? 'documento anterior no tiene tiempos registrados' : 'documentos anteriores no tienen tiempos registrados'}.`}</p>
    <section className="card table-card"><div className="panel-heading"><h3>Reglas con hallazgos</h3><span className="muted small">{s.distinct_rules} reglas distintas con hallazgos</span></div><div className="table-scroll"><table className="compact-table"><thead><tr><th>Regla</th><th>Expresión o criterio</th><th>Coincidencias</th><th>Documentos</th><th>Distribución</th></tr></thead><tbody>{s.rules.map(r => <tr key={r.id}><td><span className="rule-id">{r.id}</span></td><td>{r.name}</td><td>{number(r.count)}</td><td>{number(r.documents)}</td><td><div className="rule-bar" aria-label={`${r.count} de ${s.findings} hallazgos`}><span style={{width:`${100*r.count/Math.max(1,s.findings)}%`}}/></div></td></tr>)}</tbody></table>{!s.rules.length && <p className="table-empty">Todavía no hay hallazgos en los documentos analizados.</p>}</div></section>
    <section className="card table-card"><div className="panel-heading"><h3>Documentos del proyecto</h3></div><div className="table-scroll"><table className="compact-table"><thead><tr><th>Documento</th><th>Estado</th><th>Tamaño</th><th>Frases</th><th>Hallazgos</th><th>Pendientes</th><th>Procesamiento</th></tr></thead><tbody>{documents.map(d => <tr key={d.id}><td><button className="text-button" onClick={()=>onOpen(d.id)}>{d.name}</button></td><td><span className={`pill ${d.status==='completed'?'green':d.status==='failed'?'red':'blue'}`}>{stageNames[d.status]}</span></td><td>{formatBytes(d.size_bytes)}</td><td>{d.statistics ? number(d.statistics.sentences) : '—'}</td><td>{d.statistics ? number(d.findings) : '—'}</td><td>{d.statistics ? number(d.pending) : '—'}</td><td>{formatTime(d.processing_ms)}</td></tr>)}</tbody></table>{!documents.length && <p className="table-empty">Sube el primer PDF de este proyecto para ver sus estadísticas.</p>}</div></section>
    <details className="card project-edit"><summary>Editar nombre y descripción del proyecto</summary><ProjectForm key={project.name+project.description} project={project} busy={busy} onSave={onSave}/></details>
    <DeleteProject key={project.id} project={project} busy={busy} onDelete={onDelete}/>
  </>;
}
function DeleteProject({ project, busy, onDelete, compact=false }) {
  const [confirm, setConfirm] = useState(false);
  const s = project.statistics;
  return <section className={compact ? "project-delete-control" : "card danger-zone"}>{(!compact || confirm) && <><h3>Eliminar proyecto</h3><p>Se eliminará «{project.name}» con sus PDF, análisis y decisiones de la base activa. Las copias de seguridad existentes conservan su contenido.</p></>}
    {confirm ? <div role="group" aria-label="Confirmar borrado del proyecto"><p role="alert">Vas a borrar {s.documents} {s.documents === 1 ? 'documento' : 'documentos'} y todas sus revisiones.{s.working > 0 && ` Se retirarán también ${s.working} trabajos en proceso.`} Esta acción no se puede deshacer desde la aplicación.</p><div className="decision-actions"><button className="danger" disabled={busy} onClick={onDelete}>Borrar «{project.name}» definitivamente</button><button disabled={busy} onClick={() => setConfirm(false)}>Cancelar</button></div></div>
      : <button className="danger" aria-label={`Eliminar proyecto ${project.name}`} disabled={busy} onClick={() => setConfirm(true)}>{compact ? "Eliminar" : "Eliminar proyecto"}</button>}
  </section>;
}
