import React,{useEffect,useState} from 'react';
const labels={pending:'Pendiente',approved:'Aprobada',kept:'Conservada'};
export default function Suggestions({document,page,selectedId,onSelect,onSave,busy}){
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[pageOnly,setPageOnly]=useState(false),[offset,setOffset]=useState(0);
 const findings=document.result?.findings||[],decisions=new Map(document.decisions.map(d=>[d.finding_id,d]));
 const visible=findings.filter(f=>(filter==='all'||(decisions.get(f.id)?.status||'pending')===filter)&&(!pageOnly||f.page===page)&&`${f.phrase} ${f.rule_name} ${f.replacement||''}`.toLocaleLowerCase('es-ES').includes(search.toLocaleLowerCase('es-ES')));
 useEffect(()=>setOffset(0),[filter,search,pageOnly,page]);
 useEffect(()=>{const index=visible.findIndex(f=>f.id===selectedId);if(index>=0)setOffset(Math.floor(index/40)*40);else if(selectedId){setFilter('all');setSearch('');}},[selectedId]);
 const start=Math.min(offset,Math.max(0,Math.floor((visible.length-1)/40)*40));
 return <><div className="suggestion-filters"><input type="search" aria-label="Buscar sugerencias" placeholder="Buscar sugerencia…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Estado de las sugerencias" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="checkbox"><input type="checkbox" checked={pageOnly} onChange={e=>setPageOnly(e.target.checked)}/>Solo esta página</label></div>
 <div className="suggestion-scroll"><table className="compact-table suggestions-table"><thead><tr><th aria-label="Detalle"/><th>Pág.</th><th>Texto y propuesta</th><th>Decisión</th></tr></thead><tbody>{visible.slice(start,start+40).map(f=><Suggestion key={`${f.id}:${decisions.get(f.id)?.updated_at||''}`} finding={f} block={document.result.blocks.find(b=>b.id===f.block_id)} decision={decisions.get(f.id)} selected={f.id===selectedId} onSelect={onSelect} onSave={onSave} busy={busy}/>)}</tbody></table>
 {!visible.length&&<p className="table-empty">{findings.length?'No hay sugerencias con este filtro.':document.status==='completed'?'Las comprobaciones ejecutadas no encontraron candidatos. Esto no cubre todos los problemas editoriales.':'Inicia una revisión por reglas o con Ollama. Puedes seguir anotando mientras trabaja.'}</p>}</div>
 {visible.length>40&&<div className="table-pagination"><button disabled={start===0} onClick={()=>setOffset(start-40)}>Anterior</button><span>{start+1}–{Math.min(start+40,visible.length)} de {visible.length}</span><button disabled={start+40>=visible.length} onClick={()=>setOffset(start+40)}>Siguiente</button></div>}
 <p className="small muted panel-footnote">Catálogo y Ollama producen candidatos. Aprobar guarda tu decisión; el PDF original se conserva.</p></>;
}
function Suggestion({finding:f,block,decision,selected,onSelect,onSave,busy}){
 const [expanded,setExpanded]=useState(selected),[replacement,setReplacement]=useState(decision?.replacement??f.replacement??''),[note,setNote]=useState(decision?.note||''),[deleting,setDeleting]=useState(decision?.status==='approved'&&decision.replacement==='');
 useEffect(()=>{if(selected)setExpanded(true);},[selected]);
 const chars=[...(block?.text||'')],before=chars.slice(Math.max(0,f.start-400),f.start).join(''),after=chars.slice(f.end,f.end+500).join(''),status=decision?.status||'pending';
 function save(state){onSave(f,state,state==='kept'?null:deleting?'':replacement||null,note);}
 return <><tr className={selected?'selected':''}><td><button className="expand-rule" aria-label={`${expanded?'Contraer':'Ampliar'} sugerencia de página ${f.page}`} aria-expanded={expanded} onClick={()=>{setExpanded(!expanded);if(!expanded)onSelect(f);}}>{expanded?'−':'+'}</button></td><td><button className="page-link" onClick={()=>onSelect(f)}>{f.page}</button></td><td><button className="proposal-open" onClick={()=>{onSelect(f);setExpanded(true);}}><strong>{f.phrase}</strong><span>{deleting?'Eliminar fragmento':replacement||f.explanation}</span></button><small className="suggestion-origin">{f.origin==='ollama'?'Ollama':'Catálogo'} · {f.rule_id}</small></td><td><span className={`decision-state state-${status}`}>{labels[status]}</span><div className="inline-decisions"><button title="Aprobar sustitución" aria-label={`Aprobar sugerencia ${f.id}`} disabled={busy||(!deleting&&!replacement.trim())||status==='approved'} onClick={()=>save('approved')}>✓ Aprobar</button><button disabled={busy||status==='kept'} onClick={()=>save('kept')}>Conservar</button>{status!=='pending'&&<button disabled={busy} onClick={()=>save('pending')}>Reabrir</button>}</div></td></tr>
 {expanded&&<tr><td colSpan={4} className="suggestion-detail"><h3>{f.rule_name}</h3><p>{f.explanation}</p><div className="context-quote">{before}<mark>{f.phrase}</mark>{after}</div>{f.exception&&<details><summary>Cuándo conservarlo</summary><p>{f.exception}</p></details>}{f.author_safeguards?.map(w=><p key={w.code} className="safeguard-note">{w.message}</p>)}<label>Sustitución propuesta<textarea rows={2} maxLength={10000} disabled={busy||deleting} value={replacement} onChange={e=>setReplacement(e.target.value)} placeholder="Redacta el cambio si quieres proponer uno"/></label><label className="checkbox"><input type="checkbox" checked={deleting} onChange={e=>setDeleting(e.target.checked)} disabled={busy}/>Eliminar el fragmento</label>{(replacement||deleting)&&<details><summary>Leer el cambio en contexto</summary><p>{before}<mark>{deleting?'':replacement}</mark>{after}</p></details>}<label>Tu nota sobre esta sugerencia<textarea rows={2} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></label><button disabled={busy||(status==='approved'&&!deleting&&!replacement.trim())} onClick={()=>save(status)}>Guardar propuesta y nota{status==='approved'?' aprobadas':''}</button><span className="small muted"> También puedes aprobar o conservar en esta fila.</span></td></tr>}</>;
}
